server:
  servlet:
    context-path: "/api"

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/users}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/master.xml
    default-schema: public

springdoc:
  api-docs:
    path: "/api-docs" #api will response on /api-docs
  swagger-ui:
    path: "/swagger-ui.html" # swagger: http://localhost:8080/api/swagger-ui/index.html
    version: "v1"

api:
  response-codes:
    ok:
      desc: OK
    badRequest:
      desc: BAD_REQUEST
    notFound:
      desc: NOT_FOUND
