# docker ci create image. not now...

#name: DockerCI
#on:
#  push:
#    branches:
#      - 'main'
#jobs:
#  build_docker_image:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: 17
#          distribution: 'adopt'
#      - name: Build with Gradle
#        run: ./gradlew bootJar
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Build the Docker image
#        run: |
#          chmod +x docker-compose/docker/users/githubBuild.sh
#          docker-compose/docker/users/githubBuild.sh
