services:
  psql:
    image: postgres:15
    container_name: social-psql
    ports:
#      - "внешний : внутренний"
      - "5001:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    networks:
      - social

  pgadmin:
    image: dpage/pgadmin4:6.15
    container_name: social-pgadmin
    ports:
      - "9000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.org
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped
    depends_on:
      - psql
    networks:
      - social

  users:
    container_name: social-users
    image: social-users:0.0.1
    ports:
      - "8008:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://psql:5432/users
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - psql
    networks:
      - social

  grafana:
    build: './docker/prometheus'
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - social

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    networks:
      - social

networks:
  social:
    driver: bridge
