overload:
  enabled: true
  package: yandextank.plugins.DataUploader
  token_file: "token.txt"
phantom:
  ammo_type: phantom
  address: host.docker.internal:8080
  load_profile:
    load_type: rps
    schedule: line(1, 1000, 5m)    # линейно увеличивающаяся нагрузка
      # от 1 до 1000 рпс,
    # в течение 5 минут
  ammofile: ammo.txt
console:
  enabled: true # enable console output
telegraf:
  enabled: false # let's disable telegraf monitoring for the first
