CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

create table if not exists country
(
    id        bigint generated by default as identity
        constraint pk_country_property
            primary key,
    version   integer      not null,
    name      varchar(100) not null
        unique,
    region    varchar(255),
    subregion varchar(255)
);

create table if not exists hard_skills
(
    id      bigint generated by default as identity
        constraint pk_hard_skill_property
            primary key,
    version integer      not null,
    name    varchar(255) not null
        unique
);

create table if not exists users
(
    id               uuid        default uuid_generate_v4()        not null
        constraint pk_users_property
            primary key,
    version          integer                                       not null,
    name             varchar(50)                                   not null,
    surname          varchar(50)                                   not null,
    last_name        varchar(50),
    birthdate        timestamp(6),
    email            varchar(100),
    avatar           varchar(500),
    nickname         varchar(50)                                   not null
        unique,
    phone_number     varchar(30),
    sex              varchar(10) default 'MALE'::character varying not null,
    user_description varchar(1000),
    country_id       bigint
        constraint fk_users_country_id
            references country,
    deleted          boolean     default false                     not null
);

create table if not exists user_followers
(
    user_id     uuid not null
        constraint fk_users_followers_user_id
            references users,
    follower_id uuid not null
        constraint fk_users_followers_follower_id
            references users,
    constraint pk_user_followers
        primary key (user_id, follower_id)
);

create table if not exists user_hard_skills
(
    user_id       uuid   not null
        constraint fk_skills_user_id
            references users,
    hard_skill_id bigint not null
        constraint fk_skills_hard_skill_id
            references hard_skills
);

